name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v3
      - name: Install WASM32 Target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: just build-release
      - name: Pre-release
        run: |
          cd target/wasm32-unknown-unknown/release
          mv dprint_plugin_classname_wrap.wasm plugin.wasm
      - name: Generate WASM Checksum
        run: |
          cd target/wasm32-unknown-unknown/release
          sha256sum plugin.wasm > plugin.wasm.sha256
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dprint_plugin_classname_wrap-${{ github.ref_name }}
          path: |
            target/wasm32-unknown-unknown/release/plugin.wasm
            target/wasm32-unknown-unknown/release/plugin.wasm.sha256
          compression-level: 6
          overwrite: true
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    continue-on-error: false
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true
      - name: Create Release ${{ github.ref_name }}
        uses: softprops/action-gh-release@v2.3.3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          files: dist/**/*
          make_latest: true
